train:
  epochs: 10
  accelerator: 'gpu'
  devices: 1
  seed: 42
  gradient_clip_val: 0.5
  log_every_n_steps: 2
  early_stop_patience: 10
  precision: 'high'
logger:
  mlflow_uri: http://127.0.0.1:8080
  experiment_name: AirDiffTraj
  run_name: AirDiffTraj
  tags: {'model': 'diffusion', 'dataset': 'opensky'}
data:
  dataset: mnist
  train_ratio: 0.8
  val_ratio: 0.2
  batch_size: 64
  test_batch_size: 64
  
model:
  type: "simple"
  attr_dim: 8
  guidance_scale: 3
  in_channels: 2
  out_ch: 2
  ch: 128
  ch_mult: [ 1, 2, 2, 2 ]
  num_res_blocks: 2
  attn_resolutions: [ 16 ]
  dropout: 0.1
  traj_length: 200
  lr: 2e-4
  diffusion:
    beta_schedule: 'linear'
    beta_start: 0.0001
    beta_end: 0.05
    num_diffusion_timesteps: 500
    ema: True
    ema_rate: 0.9999