train:
  epochs: 10
  accelerator: 'gpu'
  devices: 1
  seed: 37
  gradient_clip_val: 0.5
  log_every_n_steps: 2
  early_stop_patience: 10
  precision: 'high'
logger:
  mlflow_uri: http://127.0.0.1:8080
  experiment_name: diffusion
  run_name: diffusion
  tags: {'model': 'cond_vae', 'dataset': 'cifar10'}
data:
  dataset: mnist
  train_ratio: 0.8
  val_ratio: 0.2
  batch_size: 64
  test_batch_size: 64
  
model:
  type: diffusion
  z_dim: 256
  hidden_dim: 512
  lr: 0.0001
  lr_step_size: 200
  lr_gamma: 0.5
  dropout: 0.0
  llv_coef: 1.0
  kld_coef: 1.0
  scale: 1.0
  conditional: True
  num_classes: 10
