train:
  epochs: 200
  accelerator: 'auto'
  devices: '1'
  seed: 42
  gradient_clip_val: 0.5
  log_every_n_steps: 2
  early_stop_patience: 10
  precision: 'high'
logger:
  mlflow_uri: http://100.64.0.15:5000
  experiment_name: AirDiffTraj
  run_name: AirDiffTraj
  tags: {'model': 'diffusion', 'dataset': 'opensky'}
data:
  dataset: opensky
  data_path: ./data/traffic.pkl
  features: [ 'latitude', 'longitude', 'altitude', 'timedelta' ]
  #features: [ 'groundspeed', 'track_cos', 'track_sin', 'vertical_rate','timedelta' ]
  conditional_features:
    hour:
      type: 'cyclic'
      max_value: 24
    month:
      type: 'cyclic'
      max_value: 12
    ADEP:
      type: 'categorical'
      categories: ['EHAM', 'LIMC', 'LFPG', 'EGKK', 'LIRF', 'LOWW', 'EGLL', 'ESSA', 'EDDF', 'EDDT']
    ADES:
      type: 'categorical'
      categories: ['EHAM', 'LIMC', 'LFPG', 'EGKK', 'LIRF', 'LOWW', 'EGLL', 'ESSA', 'EDDF', 'EDDT']
    cluster:
      type: 'categorical'
      categories: [0, 1, 2, 3, 4]
  weather_grid:
    variables : ['v_component_of_wind', 'u_component_of_wind', 'vertical_velocity', 'temperature']
    #variables : ['v_component_of_wind', 'u_component_of_wind', 'vertical_velocity', 'temperature', 'total_precipitation', 'total_cloud_cover']
    resolution: 1
  data_shape: 'image'
  train_ratio: 0.8
  val_ratio: 0.2
  batch_size: 64
  test_batch_size: 128
  length: 200
  down_sample_factor: 30
  info_features: [ ] # These are useless
  info_index: -1 # Useless
  
model:
  type: "simple"
  attr_dim: 8
  guidance_scale: 3
  in_channels: 4
  out_ch: 4
  ch: 256
  ch_mult: [ 1, 2, 2, 4 ]
  num_res_blocks: 2
  attn_resolutions: [ 16, 8]
  dropout: 0.1
  #traj_length: 4633
  #traj_length: 2316
  lr: 0.0001
  resamp_with_conv: True
  diffusion:
    beta_schedule: 'linear'
    beta_start: 0.0001
    beta_end: 0.5
    num_diffusion_timesteps: 600
    ema: True
    ema_rate: 0.9999
  weather_grid: True
