train:
  epochs: 100
  accelerator: 'gpu'
  devices: 1
  seed: 37
  gradient_clip_val: 0.5
  log_every_n_steps: 2
  early_stop_patience: 60
  precision: 'high'
logger:
  mlflow_uri: http://100.64.0.15:7979
  experiment_name: AirLatFMTraj track
  run_name: AirLatFMTraj track
  tags: {'model': 'Latent Flow Matching', 'dataset': 'opensky', 'weather': False, "model_id": "norm_landing_4"}
  
model:
  type: "LatFM"
  vae: "./artifacts/VAE_naive"
  #h_dims: [128, 256, 256, 128]
  #encoding_dim: 256
  #encoding_dim: 128
  lr: 4.9e-5
  lr_step_size: 200
  lr_gamma: 0.5
  attr_dim: 128
  guidance_scale: 3.0
  in_channels: 8
  out_ch: 8
  ch: 64
  ch_mult: [ 1, 2, 4, 4, 8 ]
  num_res_blocks: 8
  attn_resolutions: [32, 16]
  dropout: 0.1
  resamp_with_conv: True
  cnn: True
  diffusion:
    ema: True
    #ema_rate: 0.999999
    ema_rate: 0.99999
  weather_config:
    weather_grid: False
    variables: 1
    levels: 1
    lon: 5
    lat: 5
    type: "ADES"
      #type: "Function"
      #type: "Grid"
      #lon: 81
      #lat: 106
