train:
  epochs: 100
  accelerator: 'auto'
  devices: '1'
  seed: 42
  gradient_clip_val: 0.5
  log_every_n_steps: 2
  early_stop_patience: 10
  precision: 'high'
logger:
  mlflow_uri: http://100.64.0.15:5000
  experiment_name: AirDiffTraj
  run_name: AirDiffTraj
  tags: {'model': 'diffusion', 'dataset': 'opensky'}
data:
  dataset: opensky
  data_path: ./data/traffic.pkl
  features: [ 'latitude', 'longitude', 'altitude', 'timedelta' ]
  conditional_features:
    hour:
      type: 'cyclic'
      max_value: 24
    month:
      type: 'cyclic'
      max_value: 12
    ADEP:
      type: 'categorical'
    ADES:
      type: 'categorical'
  data_shape: 'image'
  train_ratio: 0.8
  val_ratio: 0.2
  batch_size: 256
  test_batch_size: 32
  length: 200
  down_sample_factor: 30
  info_features: [ ] # These are useless
  info_index: -1 # Useless
  
model:
  type: "simple"
  attr_dim: 8
  guidance_scale: 3
  in_channels: 4
  out_ch: 4
  ch: 128
  ch_mult: [ 1, 2, 2, 2 ]
  num_res_blocks: 2
  attn_resolutions: [ 16 ]
  dropout: 0.1
  #traj_length: 4633
  #traj_length: 2316
  lr: 0.0002
  resamp_with_conv: True
  diffusion:
    beta_schedule: 'linear'
    beta_start: 0.0001
    beta_end: 0.05
    num_diffusion_timesteps: 500
    ema: True
    ema_rate: 0.9999
