train:
  epochs: 100
  accelerator: 'auto'
  devices: '1'
  seed: 42
  gradient_clip_val: 0.5
  log_every_n_steps: 2
  early_stop_patience: 40
  precision: 'high'
logger:
  mlflow_uri: http://100.64.0.15:7979
  experiment_name: AirDiffTraj
  run_name: AirDiffTraj
  tags: {'model': 'diffusion', 'dataset': 'opensky', 'weather': False}
  
model:
  type: "DDIM"
  cnn: True
  attr_dim: 64
  guidance_scale: 1
  in_channels: 6
  out_ch: 6
  ch: 128
  ch_mult: [ 1, 2, 2, 8 ]
  num_res_blocks: 8
  attn_resolutions: [32, 16]
  dropout: 0.1
  lr: 0.00002
  resamp_with_conv: True
  diffusion:
    beta_schedule: 'linear'
    beta_start: 0.0001            # Slightly increased for faster diffusion
    beta_end: 0.05               # Slightly increased for faster diffusion
    num_diffusion_timesteps: 500
    ema: True
    ema_rate: 0.99999
  weather_config:
    weather_grid: True
    variables: 1
    levels: 1
    lon: 5
    lat: 5
    type: "ADES"
      #type: "Function"
      #type: "Grid"
      #lon: 81
      #lat: 106
