dataset: landing
data_path: ./data/traffic.pkl
train_ratio: 0.8
val_ratio: 0.2
batch_size: 64
test_batch_size: 32
features: [ 'latitude', 'longitude', 'altitude', 'timedelta', 'groundspeed', 'track_cos', 'track_sin', 'vertical_rate']
#features: [ 'altitude', 'timedelta', 'groundspeed', 'track_cos', 'track_sin', 'vertical_rate']
#features: [ 'latitude', 'longitude', 'altitude', 'timedelta']
data_shape: 'image'
conditional_features:
  hour:
    type: 'cyclic'
    max_value: 24
  month:
    type: 'cyclic'
    max_value: 12
  day_of_week:
    type: 'cyclic'
    max_value: 6
  cumdist:
    type: 'continuous'
    last: True
    first: False
  timedelta:
    type: 'continuous'
    last: True
    first: False
  runway:
    type: 'categorical'
    #categories: ['14','16', '28', '34', 'N/A']
    categories: ['14','16', '28', '34', 'N/A', 'EIDW']
  ADEP:
    type: 'categorical'
    categories: ['01FA', '25GA', '60CO', 'BIKF', 'BIRK', 'CT09', 'CT15', 'CT29',
       'CYHU', 'CYKF', 'CYOW', 'CYUL', 'CYVR', 'CYYC', 'CYYZ', 'DAAG',
       'EBAW', 'EBBR', 'EBCI', 'EBKT', 'EBLG', 'EBMB', 'EBMO', 'EBOS',
       'EDAM', 'EDDB', 'EDDC', 'EDDF', 'EDDG', 'EDDH', 'EDDK', 'EDDL',
       'EDDM', 'EDDN', 'EDDP', 'EDDR', 'EDDS', 'EDDT', 'EDDV', 'EDDW',
       'EDFE', 'EDFH', 'EDFM', 'EDFQ', 'EDFZ', 'EDGS', 'EDHI', 'EDHK',
       'EDJA', 'EDKZ', 'EDLA', 'EDLN', 'EDLP', 'EDLV', 'EDLW', 'EDMA',
       'EDMF', 'EDMO', 'EDMS', 'EDNY', 'EDQA', 'EDRY', 'EDRZ', 'EDSB',
       'EDTB', 'EDTG', 'EDTX', 'EDTY', 'EDVE', 'EDVK', 'EDWE', 'EDXW',
       'EETN', 'EFHK', 'EFTP', 'EGAA', 'EGBB', 'EGBJ', 'EGCC', 'EGCN',
       'EGFF', 'EGGD', 'EGGP', 'EGGW', 'EGHH', 'EGHI', 'EGHQ', 'EGJB',
       'EGJJ', 'EGKB', 'EGKC', 'EGKK', 'EGLC', 'EGLF', 'EGLL', 'EGMC',
       'EGML', 'EGNH', 'EGNM', 'EGNP', 'EGNR', 'EGNS', 'EGNT', 'EGNX',
       'EGPD', 'EGPF', 'EGPH', 'EGPJ', 'EGSC', 'EGSH', 'EGSS', 'EGTC',
       'EGTE', 'EGTF', 'EGTK', 'EGWU', 'EGXE', 'EHAM', 'EHBD', 'EHBK',
       'EHEH', 'EHGG', 'EHLE', 'EHRD', 'EHTW', 'EICK', 'EIDL', 'EIDW',
       'EIKN', 'EIKY', 'EINN', 'EKAH', 'EKBI', 'EKCH', 'EKEB', 'EKRK',
       'ELLX', 'ENGM', 'EPBD', 'EPBY', 'EPGD', 'EPKK', 'EPKT', 'EPLL',
       'EPLR', 'EPMO', 'EPMR', 'EPPO', 'EPRZ', 'EPSC', 'EPSW', 'EPWA',
       'EPWR', 'ESGG', 'ESMS', 'ESMT', 'ESOW', 'ESSA', 'ESSB', 'ESTA',
       'ETAR', 'ETMN', 'EVRA', 'EYKA', 'EYKS', 'EYVI', 'EYVP', 'FACT',
       'FAGM', 'FALA', 'FAOR', 'FL84', 'GABS', 'GBYD', 'GCFV', 'GCLP',
       'GCRR', 'GMMN', 'GOBD', 'K2G1', 'KACY', 'KADS', 'KATL', 'KAUS',
       'KBED', 'KBFI', 'KBMG', 'KBOS', 'KCGF', 'KCLT', 'KCMH', 'KDEN',
       'KEWR', 'KFTY', 'KHIO', 'KHOU', 'KHPN', 'KIAD', 'KIAH', 'KILG',
       'KJFK', 'KLAS', 'KLAX', 'KLDJ', 'KMCO', 'KMIA', 'KMMU', 'KMSP',
       'KOAK', 'KOPF', 'KOQU', 'KORD', 'KORL', 'KPAE', 'KPHL', 'KPVD',
       'KRDU', 'KSEA', 'KSFO', 'KSGS', 'KSJC', 'KSTP', 'KTEB', 'KTPA',
       'KTTN', 'KUGN', 'LBWN', 'LCPH', 'LDDU', 'LDPL', 'LDSP', 'LDSR',
       'LDZA', 'LDZD', 'LE85', 'LEAL', 'LEBL', 'LECU', 'LEGE', 'LEIB',
       'LEJR', 'LELH', 'LEMD', 'LEMG', 'LEMP', 'LEMU', 'LEPA', 'LEZL',
       'LFAV', 'LFBD', 'LFBF', 'LFBO', 'LFCR', 'LFHC', 'LFKF', 'LFLB',
       'LFLC', 'LFLI', 'LFLL', 'LFLP', 'LFLY', 'LFMK', 'LFML', 'LFMN',
       'LFMV', 'LFNR', 'LFOB', 'LFOT', 'LFOZ', 'LFPB', 'LFPG', 'LFPO',
       'LFRG', 'LFRQ', 'LFSG', 'LFST', 'LFTW', 'LGAV', 'LGIR', 'LGKN',
       'LGKO', 'LGMK', 'LGRP', 'LGSM', 'LGSR', 'LHBP', 'LHSM', 'LHTL',
       'LIBD', 'LIBG', 'LIBR', 'LICC', 'LICJ', 'LICZ', 'LIEA', 'LIED',
       'LIEE', 'LIEO', 'LILG', 'LIMC', 'LIME', 'LIMF', 'LIMJ', 'LIML',
       'LIMP', 'LIMZ', 'LIPB', 'LIPE', 'LIPH', 'LIPO', 'LIPQ', 'LIPR',
       'LIPX', 'LIPZ', 'LIQL', 'LIRA', 'LIRF', 'LIRP', 'LIRQ', 'LIRZ',
       'LJLJ', 'LJMB', 'LKCS', 'LKHK', 'LKKL', 'LKKU', 'LKMT', 'LKPR',
       'LKTB', 'LKVO', 'LL59', 'LLBG', 'LMML', 'LOWG', 'LOWI', 'LOWK',
       'LOWL', 'LOWS', 'LOWW', 'LPAR', 'LPCS', 'LPEV', 'LPFR', 'LPPD',
       'LPPR', 'LPPT', 'LRBS', 'LROP', 'LSGC', 'LSGG', 'LSGK', 'LSGL',
       'LSME', 'LSMP', 'LSZA', 'LSZB', 'LSZC', 'LSZH', 'LSZL', 'LSZM',
       'LSZR', 'LTAC', 'LTBA', 'LTBW', 'LTFE', 'LTFJ', 'LYBE', 'LYBT',
       'LZIB', 'LZKZ', 'MA36', 'MMUN', 'MROC', 'MRPV', 'OBBI', 'OERK',
       'OLBA', 'OMAA', 'OMAD', 'OMDB', 'OMDW', 'OMRK', 'OTBD', 'OTHH',
       'RJAA', 'RJAK', 'RJBB', 'RKSI', 'RPLL', 'SAEZ', 'SBGR', 'SBSJ',
       'TLPL', 'TVSC', 'TXKF', 'UBBB', 'UKBB', 'UKKK', 'ULLI', 'UUDD',
       'UUEE', 'UUMO', 'UUWW', 'UWKD', 'VABB', 'VAJJ', 'VAPO', 'VHHH',
       'VIDP', 'VTBD', 'VTBS', 'WMKK', 'WSSS', 'YMML', 'ZGSZ', 'ZZZZ']
  ADES:
    type: 'categorical'
    categories: ['LSZH', 'EIDW']
metar: False
weather_grid:
  #variables : ['v_component_of_wind', 'u_component_of_wind', 'vertical_velocity', 'temperature']
  #variables : ['v_component_of_wind', 'u_component_of_wind', 'vertical_velocity', 'temperature', 'total_precipitation', 'total_cloud_cover']
  variables : ['total_cloud_cover']
  resolution: 1
  function: True
