dataset: landing
data_path: ./data/traffic.pkl
train_ratio: 0.8
val_ratio: 0.2
batch_size: 1024
#batch_size: 256
test_batch_size: 32
#features: [ 'latitude', 'longitude', 'altitude', 'timedelta', 'groundspeed', 'track_cos', 'track_sin', 'vertical_rate']
features: [ 'altitude', 'timedelta', 'groundspeed', 'track_cos', 'track_sin', 'vertical_rate']
#features: [ 'latitude', 'longitude', 'altitude', 'timedelta']
#scaler_path: "/mnt/data/synthair/synthair_diffusion/data/resampled/scalers/7_datasets_utm_standard.gz"
data_shape: 'image'
conditional_features:
  hour:
    type: 'cyclic'
    max_value: 24
  month:
    type: 'cyclic'
    max_value: 12
  day_of_week:
    type: 'cyclic'
    max_value: 6
    #cumdist:
    #type: 'continuous'
    #last: True
    #first: False
  timedelta:
    type: 'continuous'
    last: True
    first: False
  runway:
    type: 'categorical'
    categories: ['14','16', '28', '34', 'N/A', "EHAM", "LFPG", "EIDW", "EGLL", "EGLC", "LFBO"]
  ADEP:
    type: 'categorical'
    categories: ['00GA', '01FA', '02XS', '19GA', '22CO', '24PA', '25GA', '32PN',
       '38OI', '4GE2', '4OH4', '51GA', '60CO', '63OH', '6NJ9', '71KY',
       '78MI', '7CO3', '7PS7', '88PA', '89GE', '8KY6', '96CO', '98VA',
       'AZ90', 'BIKF', 'BIRK', 'CCV4', 'CD14', 'CEF4', 'CFX8', 'CHF2',
       'CNV9', 'CO56', 'CPR2', 'CT09', 'CT15', 'CT29', 'CYHU', 'CYKF',
       'CYOW', 'CYQB', 'CYRO', 'CYUL', 'CYVR', 'CYYC', 'CYYT', 'CYYZ',
       'DAAG', 'DAAX', 'DAOI', 'DTTA', 'EBAW', 'EBBR', 'EBCI', 'EBFS',
       'EBKT', 'EBLG', 'EBMB', 'EBMO', 'EBOS', 'EDAM', 'EDAQ', 'EDAZ',
       'EDDB', 'EDDC', 'EDDE', 'EDDF', 'EDDG', 'EDDH', 'EDDK', 'EDDL',
       'EDDM', 'EDDN', 'EDDP', 'EDDR', 'EDDS', 'EDDT', 'EDDV', 'EDDW',
       'EDFE', 'EDFH', 'EDFM', 'EDFQ', 'EDFZ', 'EDGS', 'EDHI', 'EDHK',
       'EDHL', 'EDJA', 'EDKZ', 'EDLA', 'EDLN', 'EDLP', 'EDLR', 'EDLV',
       'EDLW', 'EDMA', 'EDMF', 'EDMO', 'EDMS', 'EDNY', 'EDPI', 'EDQA',
       'EDQG', 'EDRY', 'EDRZ', 'EDSB', 'EDSW', 'EDTB', 'EDTG', 'EDTM',
       'EDTX', 'EDTY', 'EDVE', 'EDVK', 'EDWE', 'EDWI', 'EDXW', 'EETN',
       'EFHK', 'EFTP', 'EFTU', 'EGAA', 'EGAC', 'EGAD', 'EGBB', 'EGBJ',
       'EGCC', 'EGCN', 'EGFF', 'EGGD', 'EGGP', 'EGGW', 'EGHH', 'EGHI',
       'EGHQ', 'EGHR', 'EGJB', 'EGJJ', 'EGKA', 'EGKB', 'EGKC', 'EGKK',
       'EGKR', 'EGLC', 'EGLD', 'EGLF', 'EGLL', 'EGLM', 'EGMC', 'EGML',
       'EGNH', 'EGNJ', 'EGNM', 'EGNP', 'EGNR', 'EGNS', 'EGNT', 'EGNV',
       'EGNX', 'EGPD', 'EGPF', 'EGPG', 'EGPH', 'EGPJ', 'EGPK', 'EGSC',
       'EGSH', 'EGSS', 'EGTB', 'EGTC', 'EGTE', 'EGTF', 'EGTK', 'EGTU',
       'EGVN', 'EGWU', 'EGXE', 'EHAM', 'EHBD', 'EHBK', 'EHDL', 'EHEH',
       'EHGG', 'EHGR', 'EHKD', 'EHLE', 'EHMZ', 'EHRD', 'EHTE', 'EHTW',
       'EHTX', 'EHVK', 'EHWO', 'EICK', 'EIDL', 'EIDW', 'EIKN', 'EIKY',
       'EINN', 'EIWT', 'EKAH', 'EKBI', 'EKCH', 'EKEB', 'EKRK', 'EKSB',
       'EKYT', 'ELLX', 'ENAL', 'ENBR', 'ENGM', 'ENHD', 'ENUL', 'ENVA',
       'ENZV', 'EPBD', 'EPBY', 'EPGD', 'EPKK', 'EPKT', 'EPLL', 'EPLR',
       'EPMO', 'EPMR', 'EPPO', 'EPRZ', 'EPSC', 'EPSW', 'EPWA', 'EPWR',
       'ESGG', 'ESMS', 'ESMT', 'ESMX', 'ESOW', 'ESSA', 'ESSB', 'ESSD',
       'ESTA', 'ETAR', 'ETMN', 'ETSI', 'EVRA', 'EYKA', 'EYKS', 'EYVI',
       'EYVP', 'FABB', 'FACT', 'FAGM', 'FALA', 'FAOR', 'FARA', 'FASI',
       'FATA', 'FAWK', 'FL84', 'GA92', 'GA94', 'GA95', 'GABS', 'GBYD',
       'GCFV', 'GCLA', 'GCLP', 'GCRR', 'GGOV', 'GMME', 'GMMN', 'GMMT',
       'GMTT', 'GOBD', 'GQNO', 'GUCY', 'GVAC', 'GVBA', 'GVNP', 'K06C',
       'K2G1', 'KACY', 'KADS', 'KADW', 'KATL', 'KAUS', 'KBED', 'KBFI',
       'KBMG', 'KBNA', 'KBOS', 'KBUR', 'KBWI', 'KCGF', 'KCLT', 'KCMH',
       'KCNO', 'KCVG', 'KDAL', 'KDEN', 'KDFW', 'KEWR', 'KFLL', 'KFRG',
       'KFTG', 'KFTY', 'KGYR', 'KHIO', 'KHOU', 'KHPN', 'KIAD', 'KIAH',
       'KILG', 'KIND', 'KJFK', 'KLAS', 'KLAX', 'KLCK', 'KLDJ', 'KLGA',
       'KMCO', 'KMDW', 'KMIA', 'KMMU', 'KMSP', 'KOAK', 'KOPF', 'KOQU',
       'KORD', 'KORL', 'KPAE', 'KPDK', 'KPDX', 'KPHL', 'KPHX', 'KPIT',
       'KPVD', 'KRDU', 'KROG', 'KS50', 'KSAN', 'KSEA', 'KSFO', 'KSGS',
       'KSJC', 'KSLC', 'KSTP', 'KTEB', 'KTMB', 'KTPA', 'KTTN', 'KUGN',
       'KVNY', 'LBBG', 'LBSF', 'LBWN', 'LCPH', 'LDDU', 'LDPL', 'LDSP',
       'LDSR', 'LDZA', 'LDZD', 'LE85', 'LEAL', 'LEBL', 'LECU', 'LEGE',
       'LEIB', 'LEJR', 'LELH', 'LELN', 'LEMD', 'LEMG', 'LEMP', 'LEMU',
       'LEPA', 'LETO', 'LEVD', 'LEZG', 'LEZL', 'LFAT', 'LFAV', 'LFBD',
       'LFBF', 'LFBO', 'LFCR', 'LFFZ', 'LFHC', 'LFHJ', 'LFJL', 'LFJR',
       'LFKF', 'LFKJ', 'LFLB', 'LFLC', 'LFLI', 'LFLL', 'LFLP', 'LFLY',
       'LFME', 'LFMI', 'LFMK', 'LFML', 'LFMN', 'LFMV', 'LFNG', 'LFNL',
       'LFNR', 'LFOB', 'LFOE', 'LFOH', 'LFOK', 'LFOT', 'LFOZ', 'LFPB',
       'LFPG', 'LFPM', 'LFPN', 'LFPO', 'LFPP', 'LFPV', 'LFQK', 'LFQQ',
       'LFRB', 'LFRG', 'LFRJ', 'LFRL', 'LFRN', 'LFRQ', 'LFRS', 'LFSG',
       'LFSN', 'LFST', 'LFTW', 'LGAV', 'LGIR', 'LGKN', 'LGKO', 'LGMK',
       'LGRP', 'LGSA', 'LGSM', 'LGSR', 'LHBP', 'LHSM', 'LHTL', 'LIAR',
       'LIBD', 'LIBG', 'LIBR', 'LICB', 'LICC', 'LICJ', 'LICZ', 'LIEA',
       'LIED', 'LIEE', 'LIEO', 'LILG', 'LIMB', 'LIMC', 'LIME', 'LIMF',
       'LIMJ', 'LIML', 'LIMP', 'LIMZ', 'LIPB', 'LIPE', 'LIPH', 'LIPO',
       'LIPQ', 'LIPR', 'LIPX', 'LIPZ', 'LIQL', 'LIRA', 'LIRF', 'LIRP',
       'LIRQ', 'LIRZ', 'LJLJ', 'LJMB', 'LKCS', 'LKHK', 'LKKL', 'LKKU',
       'LKMT', 'LKPC', 'LKPD', 'LKPM', 'LKPR', 'LKSN', 'LKTB', 'LKVO',
       'LL59', 'LLBG', 'LLSD', 'LMML', 'LOWG', 'LOWI', 'LOWK', 'LOWL',
       'LOWS', 'LOWW', 'LPAR', 'LPCS', 'LPEV', 'LPFR', 'LPMA', 'LPPD',
       'LPPR', 'LPPT', 'LRBS', 'LROP', 'LRSB', 'LSGC', 'LSGG', 'LSGK',
       'LSGL', 'LSME', 'LSMP', 'LSZA', 'LSZB', 'LSZC', 'LSZH', 'LSZL',
       'LSZM', 'LSZR', 'LTAC', 'LTBA', 'LTBW', 'LTFE', 'LTFJ', 'LYBE',
       'LYBT', 'LZIB', 'LZKZ', 'MA36', 'MI53', 'MMUN', 'MROC', 'MRPV',
       'NZCH', 'OA16', 'OBBI', 'OEDF', 'OERK', 'OETH', 'OKBK', 'OLBA',
       'OMAA', 'OMAD', 'OMAF', 'OMDB', 'OMDW', 'OMRK', 'OMSJ', 'OTBD',
       'OTBH', 'OTHH', 'PANC', 'RCTP', 'RJAA', 'RJAK', 'RJBB', 'RJTK',
       'RJTL', 'RJTT', 'RKSI', 'RKSS', 'RPLL', 'RPLS', 'SAEZ', 'SBBR',
       'SBGL', 'SBGR', 'SBKP', 'SBMT', 'SBSJ', 'SEAS', 'SEQM', 'SKBO',
       'SKGY', 'SKMA', 'SPJC', 'TBPB', 'TLPL', 'TVSC', 'TXKF', 'UAAA',
       'UAII', 'UBBB', 'UDYZ', 'UKBB', 'UKKK', 'ULLI', 'ULLP', 'UTTT',
       'UUBW', 'UUDD', 'UUEE', 'UUMO', 'UUWW', 'UWKD', 'VABB', 'VAJJ',
       'VAPO', 'VGTJ', 'VGZR', 'VHHH', 'VIDP', 'VOBL', 'VOMM', 'VTBD',
       'VTBS', 'WBSB', 'WMKK', 'WSAC', 'WSSS', 'YBBN', 'YMML', 'YPPH',
       'YSSY', 'ZGGG', 'ZGSZ', 'ZUCK', 'ZZZZ']
  ADES:
    type: 'categorical'
    categories: ["EHAM", "LFPG", "EIDW", "EGLL", "EGLC", "LFBO", "LSZH"]
metar: False
weather_grid:
  #variables : ['v_component_of_wind', 'u_component_of_wind', 'vertical_velocity', 'temperature']
  #variables : ['v_component_of_wind', 'u_component_of_wind', 'vertical_velocity', 'temperature', 'total_precipitation', 'total_cloud_cover']
  enabled: False
  variables : ['total_cloud_cover']
