train:
  epochs: 100
  accelerator: 'auto'
  devices: 1
  seed: 42
  gradient_clip_val: 0.5
  log_every_n_steps: 2
  early_stop_patience: 10
  precision: 'high'
logger:
  mlflow_uri: http://100.64.0.15:7979
  experiment_name: VAE
  run_name: VAE
  tags: {'model': 'vae', 'dataset': 'dublin', 'weather': False, 'model_id': 'vae_norm'}
  #experiment_name: TCVAE
  #run_name: TCVAE
  #tags: {'model': 'tcvae', 'dataset': 'opensky'}
model:
  #type: "TCVAE"
  type: "VAE"
  #h_dims: [256, 512, 512, 256]
  h_dims: [512, 512, 512, 512]
  #encoding_dim: 256
  encoding_dim: 512
  #encoding_dim: 64
  lr: 0.0001
  lr_step_size: 200
  lr_gamma: 0.5
  dropout: 0.0
  in_channels: 8
  out_ch: 8
  llv_coef: 1.0
  #kld_coef: 1.0
  kld_coef: 0.00000001
  reg_pseudo: False
  scale: 1.0
  fix_prior: True
  n_components: 1000
  prior: 'vampprior'
  sampling_factor: 1
  kernel_size: 16
  #kernel_size: 32
  dilation_base: 2
  exemplar_path: ./data/traffic.pkl
  conditional: False
  weather_config:
    weather_grid: False
    variables: 4
    levels: 4
    lon: 5
    lat: 5
    type: "ADES"
