train:
  epochs: 300
  accelerator: 'auto'
  devices: '1'
  seed: 42
  gradient_clip_val: 0.5
  log_every_n_steps: 2
  early_stop_patience: 40
  precision: 'high'
logger:
  mlflow_uri: http://100.64.0.15:7979
  experiment_name: TCVAE
  run_name: TCVAE
  tags: {'model': 'tcvae', 'dataset': 'opensky'}
data:
  dataset: opensky
  data_path: ./data/traffic.pkl
  #features: [ 'latitude', 'longitude', 'altitude', 'timedelta']
  #features: [ 'latitude', 'longitude', 'altitude', 'groundspeed', 'track']
  #features: [ 'latitude', 'longitude', 'altitude', 'groundspeed', 'track_cos', 'track_sin']
  features: [ 'latitude', 'longitude', 'altitude', 'timedelta', 'groundspeed', 'track_cos', 'track_sin', 'vertical_rate']
  #features: [ 'latitude', 'longitude', 'altitude', 'timedelta', 'groundspeed', 'track_cos', 'track_sin']
  #features: [ 'latitude_sin', 'latitude_cos', 'longitude_sin', 'longitude_cos', 'altitude', 'timedelta', 'groundspeed', 'track']
  #features: [ 'groundspeed', 'track_cos', 'track_sin', 'vertical_rate','timedelta' ]
  conditional_features:
    hour:
      type: 'cyclic'
      max_value: 24
    month:
      type: 'cyclic'
      max_value: 12
    day_of_week:
      type: 'cyclic'
      max_value: 6
    ADEP:
      type: 'categorical'
      categories: ['EHAM', 'LIMC', 'LFPG', 'EGKK', 'LIRF', 'LOWW', 'EGLL', 'ESSA', 'EDDF', 'EDDT']
    ADES:
      type: 'categorical'
      categories: ['EHAM', 'LIMC', 'LFPG', 'EGKK', 'LIRF', 'LOWW', 'EGLL', 'ESSA', 'EDDF', 'EDDT']
      #phase:
      #type: 'categorical'
      #categories: ['CLIMB', 'LEVEL', 'DESCENT', 'NA', 'CRUISE']
    cluster:
      type: 'categorical'
      categories: [0, 1, 2, 3, 4]
      ##timedelta:
      #type: 'continuous'
    cumdist:
      type: 'continuous'
      last: True
      first: False
    timedelta:
      type: 'continuous'
      last: True
      first: False
      #groundspeed:
      #type: 'continuous'
      #track:
      #type: 'continuous'
  weather_grid:
    #variables : ['v_component_of_wind', 'u_component_of_wind', 'vertical_velocity', 'temperature']
    variables : ['v_component_of_wind', 'u_component_of_wind', 'vertical_velocity', 'temperature', 'total_precipitation', 'total_cloud_cover']
    resolution: 1
    function: True
  data_shape: 'image'
  train_ratio: 0.8
  val_ratio: 0.2
  batch_size: 512
  test_batch_size: 32
  length: 200
  
model:
  type: "TCVAE"
  h_dims: [256, 256, 256, 256]
  encoding_dim: 256
  #encoding_dim: 128
  lr: 0.001
  lr_step_size: 200
  lr_gamma: 0.5
  dropout: 0.1
  in_channels: 8
  out_ch: 8
  llv_coef: 1.0
  kld_coef: 0.0001
  reg_pseudo: False
  scale: 1.0
  fix_prior: True
  n_components: 1000
  prior: 'vampprior'
  sampling_factor: 1
  kernel_size: 16
  #kernel_size: 32
  dilation_base: 2
  exemplar_path: ./data/traffic.pkl
  conditional: True
